server:
  port: 22000

spring:
  main:
    banner-mode: off
  application:
    name: mcp-nacos-register-extensions-example
  ai:
    mcp:
      server:
        name: webflux-mcp-server-yingzi
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        instructions: "This reactive server provides time information tools and resources"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        protocol: SSE
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}

    alibaba:
      mcp:
        nacos:
          namespace: 8237f998-2f01-4cf8-bfc1-64012d09cce2
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos
          register:
            enabled: true
            service-group: mcp-server
            service-name: webflux-mcp-server-yingzi
    toolcalling:
      weather:
        api-key: ${WEATHER_API_KEY}
